media:
  input: .
  output: /
  categories: [image]
  rename: safe

content:
  - name: main-pages
    label: Website Pages
    type: group
    items:
      - name: home
        label: Home
        type: file
        path: index.html
        format: code
        operations:
          delete: false

      - name: hunting
        label: Hunting
        type: file
        path: hunting.html
        format: code
        operations:
          delete: false

      - name: fishing
        label: Fishing
        type: file
        path: fishing.html
        format: code
        operations:
          delete: false

      - name: camping
        label: Camping
        type: file
        path: camping.html
        format: code
        operations:
          delete: false

      - name: survival
        label: Survival
        type: file
        path: survival.html
        format: code
        operations:
          delete: false

      - name: gear
        label: Gear
        type: file
        path: gear.html
        format: code
        operations:
          delete: false

      - name: guides
        label: Guides
        type: file
        path: guides.html
        format: code
        operations:
          delete: false

      - name: about
        label: About
        type: file
        path: about.html
        format: code
        operations:
          delete: false